const userTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_UP_ERROR: "SIGN_UP_ERROR",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
  RESET_PASS_SUCCESS: "RESET_PASS_SUCCESS",
  RESET_PASS_ERROR: "RESET_PASS_ERROR",
  RESET_AUTH_FORM: "RESET_AUTH_FORM",
};

export default userTypes;
